MyEnterprise-web/src/main/java/com/mycompany/JSFBookServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany;

import com.mycompany.model.Author;
import javax.ejb.EJB;
import javax.faces.bean.ApplicationScoped;
import com.mycompany.model.Book;
import java.util.ArrayList;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 *
 * @author RENT
 */
@ManagedBean(name = "booksManagerBean")
@ApplicationScoped
public class JSFBookServlet {
    
    private Book book = new Book();
    private String title;
    private Integer ReleaseDate;
    private String authors;
   

    public void setAuthors(String authors) {
        this.authors = authors;
    }

    public void setBook(Book book) {
        this.book = book;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setReleaseDate(Integer ReleaseDate) {
        this.ReleaseDate = ReleaseDate;
    }


    public void setBean(BooksManagerBeanIfc bean) {
        this.bean = bean;
    }

    public Book getBook() {
        return book;
    }
    public String getAuthors() {
        return authors;
    }
   

    public String getTitle() {
        return title;
    }

    public Integer getReleaseDate() {
        return ReleaseDate;
    }


    public BooksManagerBeanIfc getBean() {
        return bean;
    }
    
    @EJB
    private BooksManagerBeanIfc bean;

    public JSFBookServlet() {

    }

    public String getText() {
        //bean.addBook("Tytul ksiazki");
        return "ksiazka";
    }
    
    public List<Book> getList() {
        return bean.getBooks();
    }
    

    //public void addBook(String bookName) {
    //    bean.addBook(bookName);
    //}
    
    public void save() {
        Book book = new Book();
        String[] names = authors.split(",");
        ArrayList<Author> booksAuthors = new ArrayList<>();
        for (String name : names) {
            Author author = new Author();
            author.setName(name);
            ArrayList<Book> arrayList = new ArrayList<>();
            arrayList.add(book);
            author.setBooks(arrayList);
            booksAuthors.add(author);
        }
        book.setReleaseDate(this.getReleaseDate());
        book.setTitle(this.getTitle());
        book.setAuthors(booksAuthors);
        bean.addBook(book);
        
    }
   

    /**
     * Creates a new instance of JSFBookServlet
     */

}

MyEnterprise-web/src/main/java/com/mycompany/RentController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany;

import com.mycompany.model.Book;
import com.mycompany.model.Rent;
import com.mycompany.model.User;
import java.util.Date;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.ApplicationScoped;
import javax.faces.bean.ManagedBean;

/**
 *
 * @author Msi
 */
@ManagedBean(name = "rentController")
@ApplicationScoped
public class RentController {
    private User user = new User();
    private Book book = new Book();
    private Date rentDate;
    private Integer id_user;
    private Integer id_book;

    public void setUser(User user) {
        this.user = user;
    }

    public void setBook(Book book) {
        this.book = book;
    }

    public void setRentDate(Date rentDate) {
        this.rentDate = rentDate;
    }

    public User getUser() {
        return user;
    }

    public Book getBook() {
        return book;
    }

    public Date getRentDate() {
        return rentDate;
    }
    
    @EJB
    private RentBeanIfc bean;
    
    public void save() {
        Rent rent = new Rent();
        rent.setBook(this.getBook());
        rent.setUser(this.getUser());
        rent.setRentDate(new Date());
        bean.rentBook(rent);
    }
    
    

    /**
     * Creates a new instance of RentController
     */
    public RentController() {
    }
    
}

MyEnterprise-web/src/main/java/com/mycompany/UserController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany;

import com.mycompany.model.Book;
import com.mycompany.model.User;
import java.util.List;
import javax.ejb.EJB;

import javax.enterprise.context.ApplicationScoped;
import javax.faces.bean.ManagedBean;

/**
 *
 * @author RENT
 */
@ManagedBean(name = "userController")
@ApplicationScoped
public class UserController {
    private User user = new User();
    private String name;

    public void setUser(User user) {
        this.user = user;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public User getUser() {
        return user;
    }

    public String getName() {
        return name;
    }

    public String getSurname() {
        return surname;
    }
    private String surname;
    
    @EJB
    private UserBeanIfc bean;
    
    
    public void save() {
        User user = new User();
        user.setName(this.getName());
        user.setSurname(this.getSurname());
        bean.addUser(user);
    }
    
    public List<User> getList() {
        return bean.getUsers();
    }
    
    
    
    /**
     * Creates a new instance of UserControler
     */
    public UserController() {
        
        
        
    }
    
}

MyEnterprise-web/src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:dataTable value="#{booksManagerBean.list}" var="book">
            <h:column>
                <f:facet name="header">
                    Title
                </f:facet>
                
                #{book.title}
            </h:column>
            <h:column>
                <f:facet name="header">
                    Author
                </f:facet>
                <ui:repeat value="#{book.authors}" var="author">
                    <h:outputText value="#{author.name}" />
                </ui:repeat>
                
            </h:column>
            <h:column>
                <f:facet name="header">
                    Type
                </f:facet>
                #{book.type}
            </h:column>
            <h:column>
                <f:facet name="header">
                    Release Date
                </f:facet>
                #{book.releaseDate}
            </h:column>
                
        </h:dataTable>
        
        <h:form>
            <h:inputText value="#{booksManagerBean.title}">Title</h:inputText>
            <h:inputText value="#{booksManagerBean.authors}">Author</h:inputText>
            <h:inputText value="#{booksManagerBean.releaseDate}">Year</h:inputText>
            <h:commandButton action="#{booksManagerBean.save}" value="Save"/>
            
        </h:form>
        
        Registrate new user:
        <h:form>
            Name: <h:inputText value="#{userController.name}"></h:inputText>
            Surname: <h:inputText value="#{userController.surname}"></h:inputText>
            <h:commandButton action="#{userController.save}" value="Add"></h:commandButton>
            
        </h:form>
        
        Rent a book
        <h:form>
            User: <h:selectOneListbox value="#{rentController.user}">
                
                <f:selectItems value="#{userController.list}" var="user" 
                               itemLabel="#{user.surname}" itemValue="#{user.id}" />
                    
            </h:selectOneListbox>
            Book: <h:selectOneListbox value="#{rentController.book}">
                
                    
                
                <f:selectItems value="#{booksManagerBean.list}" var="book" 
                               itemLabel="#{book.title}" itemValue="#{book.id}" />
                
                               
                
            </h:selectOneListbox>
            <h:commandButton action="#{rentController.save}" value="Rent"></h:commandButton>
                
            
            
        </h:form>
        
    </h:body>
</html>